# Generated by Django 5.0.6 on 2024-08-21 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Job",
            new_name="Resume",
        ),
    ]
